class AddCosasRecords < ActiveRecord::Migration
  def change
  	cosa = Cosa.create({nombre: 'Heineken Botella 355 ml', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Pringles Verdes Medianas', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Chicles Double Mint', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Skittles', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Vela Cumpleanos', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Balde Cervecero', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Granada de Chocolate', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Caja Granada', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Crow Bar Llavero', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Heineken Lata', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Caja Carton para Granada', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Budweisser Botella 350ml', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'M&Ms Chocolates', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Johnnie Walker Black 750 ml', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Portavasos Johnnie Walker ', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Agua Mineral Guitig', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Bartons Chocolate', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Caja de Madera Gr', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Caja de Madera Me', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Palanca Metalica', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Vaso Wiskero', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Whisky Stones', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Cerveza Erdinger Rubia Botella', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Cerveza Erdinger Negra Botella', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Cerveza Oettinger Negra Lata', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Cerveza Oettinger Rubia Lata', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Carne Ahumada', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Chicles Juicy Fruit', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Vodka Absolut Mini', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Medidor Coctel', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Mezclador Coctel', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Jelly Belly Coctels', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Caja Metalica Verde', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Caja Metalica Roja', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Caja Metalica Negra', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Destornillador Negro', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Destornillador Verde', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Iman ', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Jarro Cervecero para sublimar', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Jarro Cafe para sublimar', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Budweisser Lata', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Hot Tamales', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Jelly Beans Tabasco', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Tabasco Sauce Mini', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Jack Daniels', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Coca Cola Lata', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Chocolate Caoni Los Rios', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Portavaso Jack Daniels', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Brownie Chocolate', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Caja Brownie', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Energizante 4.40', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Barra Energética', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Bolsa Militar', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Barra Chocolate Artesanal', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Navaja Multiuso Generica', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Brújula linterna Llavero', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Michelada Mix', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Cerveza Pilsener Lata pequena', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Jarro Cervecero Beer Me', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Johnnie Walker Rojo', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Portavasos Johnnie Walker Rojo', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Caoni Rojo', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Cuchareta para mezclar', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Portavasos Plasticos Forma de Vinylo', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Vino tinto Gato negro pequeño', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Tabla para quesos', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Queso Hacienda Zuleta X3', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Cañitas Embutido snack', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Aceitunas la española Lata ', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Pacari Aji', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Martillo Multifuncion', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Budweisser 550 ml', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Espítiru del Ecuador clásico', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Trompo', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Dulces de Antes', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Quesadillas Alicia', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Maní Picante', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Semillas de Girasol', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Jarro Cervecero Liga', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Jarro Cervecero Nacional', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Jarro Cervecero Quito', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Jarro Cervecero Barcelona', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Jarro Cervecero Emelec', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Jarro Cervecero  Independiente del Valle', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Jarro Cervecero Aucas', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Garras de Oso', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Papa Bear portabebidas', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Heineken Lata', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Salsa Bbq Oveja Negra', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Mantel Negro Auxiliar', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Vino Emiliana', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Corcho de Vino Hat Style', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Vaso Vinero ', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Queso Maduro Ancholagua X1', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Turron Duro Negro', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Aceituna Buleria', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Chorizo Snack Espanol', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Vino Carmen', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Toblerone', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Descorchador de Vino', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Turrones la Fama', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Galletas de Mantequilla Azul', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Spin Shot ', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Rinlets', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Vino Santa Carolina 750 ml', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Galletas Walkers', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Vino 120', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Pacari Mortiño', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Pacari Rosas', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Pacari Tostado', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Pacari Yucas', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Pacari Café', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Hielera con Pinza', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Gorros Navideños', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Cobija', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Gin Bombay 750 ml ', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Agua Tónica', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Infusor', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Especies en caja Metálica', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Pacari Raw Celeste', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Bags', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Caja Madera Bag', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Corona Cerveza', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Kit Kat Chocolate', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Vino Concha Toro Exportación', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Chocolate Rocher caja regalo', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Cascaritas de Naranja', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Johnnie Negro 375 ml', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Navaja Suiza Spartan', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Linterna Mini Cotopaxi', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Jack Daniels Mini', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Habanos Coiba', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Barra Chocolate Artesanal pequeña', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Pistola molde de hielo', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Molino de Café manual', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Bolsa de Yute para café', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Lovisone Café', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'King Duque Cafe con Chocolate', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Café en grano', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Cafetera Electrica', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Jarro Cafe Because is too early', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Mix Pacari Mini X2', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Montañez Café', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Coffe Matte Personal', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Licuadora Eléctrica', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Galletas de Manzana', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'ChocoChips Bites', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Manjar ', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Mermelada Qabra', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Chocolate Liquido', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Descorchador Botella', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Mikado', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Ritter Sport Chocolate x3', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Almendras', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Calentador USB Café', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Calentador electrico Café', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Stella Artois', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Cherusker', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Paramo Roja', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Artesanal Cerveza', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Club', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Llavero Destapador', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Mani Cris Grande', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'De Todito', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Juego de Barajas Poker Star', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Fichas Poker', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Gorra Poker', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Llave Vino Decantador', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Snyders', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Vino Estancia Mendoza', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Turrones Arabian', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Ajedrez de Madera', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Tabla Cangrejos', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Mazo Cangrejos', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Delantal Cangrejos', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Tenaza Rompe Mariscos', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Patacones', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Ají Gourmet Olé', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Mini futbolín', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Pringles Verdes Grandes ', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Casco Cervecero', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Jalapeños Fortachon', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Pringles Rojas Grandes ', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Pringles Rojas Medianas', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Chocolate Takal', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Timbre Ring For me ', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Estampador de Carne', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Salsa Bbq Olé', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Chimichurrí Olé', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Encendedor de Parrillas', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Simpsons Camiseta', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Jelly Beans Cerveza', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Parrillero Set', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Bbq Spezia', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Sal Ahumada Spezia', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Pimienta Ahumada', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Golf Esferos', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'The Walking Dead Cartas', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Snickers Chocolate', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Radioactivity Protector de Bebidas', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Star Wars Camiseta XL', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Star Wars Camiseta L', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Star Wars Camiseta M', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Star Wars Camiseta S', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Flash Memory Star Wars', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Mario Bros Camiseta XL', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Mario Bros Camiseta L', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Mario Bros Camiseta M', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Mario Bros Camiseta S', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Metallica XL', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Metallica L', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Metallica M', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Metallica S', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'AcDc XL', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'AcDc L', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'AcDc M', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'AcDc S', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Beatles Camiseta XL', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Beatles Camiseta L', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Beatles Camiseta M', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Beatles Camiseta S', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Pink Floyd XL', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Pink Floyd L', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Pink Floyd M', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Pink Floyd S', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Nirvana Camiseta XL', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Nirvana Camiseta L', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Nirvana Camiseta M', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Nirvana Camiseta S', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'The Doors XL', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'The Doors L', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'The Doors M', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'The Doors S', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Cuerda para Saltar', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Mancuernas Deportivas', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'V220 energizante', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Galon ', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Espatula', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Aceite Pre Shave', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Bálsamo para barba', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'After Shave', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Jabón Avena', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Capa para afeitado', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Nerds', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Stardust', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Milky Way', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Tic Tac', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Oreo x6', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Chupete Multicolor', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Bufanda Real Madrid', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Bufanda Mánchester United', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Bufanda Bayern', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Bufanda Chelsea', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Bufanda River', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Bufanda Juventus', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Bufanda Manchester City', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Bufanda Liga', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Bufanda Quito', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Bufanda Cuenca', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Slasa Chipotle Olé', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Dip Olé', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Jalapeños Olé', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Pita Chips', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Skaladio Liga', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Jazz Caramelos', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Vino Tinto Emiliana ', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Piroulines Chocolate', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Chocolatate Tourtles', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Mixed Nuts Maní', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Bucket sin agarradera', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Cerveza Estrella Galicia', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Destapador de Cerveza Navideño Rojo', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Cerveza Latitiud Cero roja', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Destapador de Cerveza Navideño Verde', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Gomitas Haribo', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Jalapeños Olé', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Salami Snack', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Latitud Cero Verde ', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Destapador de Cerveza Navideño Verde', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Vino Blanco 120', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Bit Pan con Ajo', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Hacha Cortadora de Pizza', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Cajas Sweet Telegram', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Grill / Parrilla Portátil', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Trinche Parrillero', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Té Ingles Set x3', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Cajas Té', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Vizzio Chocolates', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Atun etiqueta Blanca', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Atun etiqueta Roja', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Atun etiqueta Amarrilla', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Atun etiqueta Azul', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Almendritas', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Yucas ', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Tornaditos', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Crunch Barra Grande', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Gin Lata', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Chicharrones', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Chifles', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Doritos Mostaza', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Latitud Cero Amarilla', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Latitud Cero Azul', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Nestle Chocolate Rojo Classic', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Pizzerolas', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
	cosa = Cosa.create({nombre: 'Yucas Rojas', cantidad_minima: 3})
	InventarioCosa.create({cosa: cosa, inventario: 0, cantidad:0})
  end
end
